version: "3"

services:
  webservice:
    build:
      context: .devcontainer
      dockerfile: Dockerfile
      args:
        # Update the VARIANT arg to pick a version of Go: 1, 1.15, 1.14
        VARIANT": "1.14"
        # Options
        INSTALL_NODE: "false"
        NODE_VERSION: "lts/*"
    command: sleep infinity
    env_file: .env
    volumes:
      - ./:/workspace
      - ./go-docker:/go

  mongo:
    image: mongo:4.2.8
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USERNAME:?MONGO_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD:?MONGO_PASSWORD}
    volumes:
      - ./mongodump:/mongodump

  mongo-express:
    image: mongo-express:0.54.0
    restart: always
    ports:
      - "10000:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_USERNAME:?MONGO_USERNAME}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_PASSWORD:?MONGO_PASSWORD}
      ME_CONFIG_MONGODB_SERVER: ${MONGO_HOST:?MONGO_HOST}
      ME_CONFIG_MONGODB_PORT: ${MONGO_PORT:?MONGO_PORT}
    depends_on:
      - mongo
