version: "3"

services:
  webservice:
    build:
      context: .devcontainer
      dockerfile: Dockerfile
      args:
        # Update the VARIANT arg to pick a version of Go: 1, 1.15, 1.14
        VARIANT": "1.14"
        # Options
        INSTALL_NODE: "false"
        NODE_VERSION: "lts/*"
    command: sleep infinity
    volumes:
      - ./:/workspace
      - ./go-docker:/go
