# This is a basic workflow to help you get started with Actions
# Reference: https://medium.com/swlh/setting-up-github-actions-for-go-project-ea84f4ed3a40

name: build

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches:
      - add-build-workflow

  pull_request:
    branches:
      - main
      - deploy

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Checkout project
        uses: actions/checkout@v2
      - name: Setup Go
        uses: actions/setup-go@v2
      - name: Install dependencies
        run: |
          go version
          go get -u golang.org/x/lint/golint
      - name: Run build
        run: go build .
      - name: Run vet & lint
        run: |
          go vet .
          golint .
